spring.application.name=jp-capacitacao-2026

spring.datasource.url=jdbc:oracle:thin:@192.168.15.6:1521/xepdb1
spring.datasource.username=system
spring.datasource.password=123A56789o
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
